### ISSUE TITLE
Major: How do you get back to view responses? & Submission fails

### ISSUE THREAD

**Issue by leemeli** [EZPick/EasyPick#23] opened 2017-06-05 01:59 UTC
Major: How do you get back to view responses? Also, submission fails when you try to use the emailed link to fill out the form

Reproduction steps:
Click create on the front page
Fill out all the required information and press submit
See “submission complete” feedback
Invite another email account to test
Access form through email
Fill out all information
“Submission failed! Please try again.”
Also don’t see a link as the maker of the meeting to view responses

**Comment by zmbc** [comment] 2017-06-05 04:20
Thanks for the report!

There are two parts to this:
- The Response submission fails. This is resolved by #27.
- There is no link to the meeting page given to the meeting creator. This is a duplicate of #25.

So, I'll set this up to be closed when #27 is merged. For the second issue, see #25.

**Closed as completed** 2017-06-05 04:46 UTC
