### ISSUE TITLE
Major: Is there a way to see the status of my meeting and other information after I create and invite people?

### ISSUE THREAD

**Issue by tgents** [EZPick/EasyPick#31] opened 2017-06-05 06:46 UTC
Unless I am missing something, I do not have access to a page that informs me of my guests, responses, and other meeting information. I can only see the create page and the response pages. As the creator, I do not get an email to link to a page like this or anything else. It seems like a serious oversight to not be able to access this information and it even looks like you planned to have one in your wiki.

**Comment by zmbc** [comment] 2017-06-05 15:17
Thanks for the report!

Surprisingly, we didn't forget to create this page, only the link to it. Because of this, I'm going to close this as a duplicate of #25.

**Closed as completed by zmbc** 2017-06-05 15:17 UTC
Labels: duplicate
